[platformio]
; Load the Secret File
extra_configs = 
    secrets.ini

[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; ----------------------------------------------------------------
; 1. UNLOCK THE 16MB FLASH & 8MB RAM
; ----------------------------------------------------------------
; Tell the compiler we have 16MB of space
board_upload.flash_size = 16MB

; Use the 16MB Partition Scheme
; (Gives ~6.5MB for App, ~6.5MB for OTA, ~3MB for Files)
board_build.partitions = default_16MB.csv

; Crucial for N16R8: Enable Octal (OPI) PSRAM mode
; "qio_opi" means Quad Flash, Octal PSRAM
board_build.arduino.memory_type = qio_opi

; ----------------------------------------------------------------
; 2. COMPILER FLAGS
; ----------------------------------------------------------------
build_flags = 
    '-D OTA_PASSWORD="${secrets.ota_password}"'
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3
    -Wno-cpp

; ----------------------------------------------------------------
; 3. LIBRARIES
; ----------------------------------------------------------------
lib_deps =
    bblanchon/ArduinoJson@^7.4.2
    majicdesigns/MD_Parola@^3.7.5
    majicdesigns/MD_MAX72XX@^3.5.1
    esphome/ESP32-audioI2S@^2.3.0
    lennarthennigs/Button2@^2.5.0
    esp32async/AsyncTCP@^3.4.9
    esp32async/ESPAsyncWebServer@^3.9.2
    ; Add button library here later if you choose one (e.g., Button2)

; ----------------------------------------------------------------
; 4. UPLOAD SETTINGS
; ----------------------------------------------------------------
monitor_speed = 115200
upload_speed = 921600  ; Fast USB upload

; UNCOMMENT THESE FOR OTA (WiFi) UPLOAD LATER:
upload_protocol = espota
upload_port = esptimecast.local
upload_flags = --auth=${secrets.ota_password}

